DEFAULT_MAPPINGS = {
    "bookmaker_names": {
        "5": "Unibet",
        "14": "10bet",
        "16": "bet365",
        "18": "Pinnacle",
        "24": "Betsafe",
        "26": "Betway",
        "27": "888sport",
        "33": "NordicBet",
        "43": "Betsson",
        "44": "Betfair Exchange",
        "147": "Dafabet",
        "417": "1xBet",
        "429": "Betfair",
        "500": "22Bet",
        "550": "GGBET",
        "575": "BetInAsia",
        "635": "BC.Game",
        "847": "Duelbits",
        "899": "Cloudbet",
        "909": "Bets.io",
        "911": "Betfury",
        "941": "Mozzartbet",
        "997": "Stake.com",
        "1011": "Megapari"
    },
    "betting_type_names": {
        "1": {"name": "1X2", "short-name": "1X2"},
        "2": {"name": "Over/Under", "short-name": "O/U"},
        "3": {"name": "Home/Away", "short-name": "Home/Away"},
        "4": {"name": "Double Chance", "short-name": "DC"},
        "5": {"name": "Asian Handicap", "short-name": "AH"},
        "6": {"name": "Draw No Bet", "short-name": "DNB"},
        "7": {"name": "To Qualify", "short-name": "TQ"},
        "8": {"name": "Correct Score", "short-name": "CS"},
        "9": {"name": "Half Time / Full Time", "short-name": "HT/FT"},
        "10": {"name": "Odd or Even", "short-name": "O/E"},
        "11": {"name": "Winner", "short-name": "Winner"},
        "12": {"name": "European Handicap", "short-name": "EH"},
        "13": {"name": "Both Teams to Score", "short-name": "BTS"}
    },
    "scope_names": {
        "1": "FT including OT",
        "2": "Full Time",
        "3": "1st Half",
        "4": "2nd Half",
        "5": "1st Period",
        "6": "2nd Period",
        "7": "3rd Period",
        "8": "1st Quarter",
        "9": "2nd Quarter",
        "10": "3rd Quarter",
        "11": "4th Quarter",
        "12": "1st Set",
        "13": "2nd Set",
        "14": "3rd Set",
        "15": "4th Set",
        "16": "5th Set",
        "17": "1st Inning",
        "18": "2nd Inning",
        "19": "3rd Inning",
        "20": "4th Inning",
        "21": "5th Inning",
        "22": "6th Inning",
        "23": "7th Inning",
        "24": "8th Inning",
        "25": "9th Inning",
        "26": "Next Set",
        "27": "Current Set",
        "28": "Next Game",
        "29": "Current Game"
    },
    "handicap_names": {
        "0": {"Name": "No Handicap"},
        "1": {"Name": "Sets"},
        "2": {"Name": "Games"},
        "3": {"Name": "Points"},
        "4": {"Name": "Frames"},
        "5": {"Name": "Goals"},
        "6": {"Name": "Runs"},
        "7": {"Name": "Legs"}
    }
}